---

# SPDX-FileCopyrightText: 2023-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.5.0"
    hooks:
      - id: "check-added-large-files"
        name: "check for added large files"
      - id: "check-ast"
        name: "check python ast"
      - id: "check-case-conflict"
        name: "check for case conflicts"
      - id: "check-docstring-first"
        name: "check docstring is first"
      - id: "check-executables-have-shebangs"
        name: "check that executables have shebangs"
      - id: "check-json"
        name: "check json"
      - id: "check-merge-conflict"
        name: "check for merge conflicts"
      - id: "check-yaml"
        name: "check yaml"
        args:
          - "--allow-multiple-documents"
          # Allow custom tags like Gitlab's "!reference" tag.
          - "--unsafe"
        exclude: "^helm/.+/templates/"
      - id: "check-symlinks"
        name: "check for broken symlinks"
      - id: "detect-private-key"
        name: "detect private key"
      - id: "fix-byte-order-marker"
        name: "fix utf-8 byte order marker"
      - id: "trailing-whitespace"
        name: "trim trailing whitespace"

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.4.0"
    hooks:
      # "Check for added large files"
      - id: "check-added-large-files"
      # "Check for merge conflicts"
      - id: "check-merge-conflict"
      # "Check Yaml"
      - id: "check-yaml"
        args:
          # Allow custom tags like Gitlab's "!reference" tag.
          - "--unsafe"
        exclude: "^helm/.+/templates/"
      # "Trim Trailing Whitespace"
      - id: "trailing-whitespace"

  # "Commit messages"
  - repo: "https://github.com/compilerla/conventional-pre-commit"
    rev: "v2.4.0"
    hooks:
      - id: "conventional-pre-commit"
        stages: ["commit-msg"]

  # "Ruff Python linter"
  - repo: "https://github.com/charliermarsh/ruff-pre-commit"
    rev: "v0.0.287"
    hooks:
      - id: "ruff"
      - id: "ruff"
        alias: "ruff-fix"
        stages: ["manual"]
        args: ["--fix"]

  # "Black Python formatter"
  - repo: "https://github.com/psf/black"
    rev: "23.7.0"
    hooks:
      - id: "black"

  # "docker-compose.yaml linter"
  - repo: "https://gitlab.com/univention/pre-commit-hooks/docker-compose-check"
    rev: "7702a8801a158b8595569dd29e2dd655d8a08310"
    hooks:
      - id: "docker-compose-check"

  # "Dockerfile linter"
  - repo: "https://gitlab.com/univention/pre-commit-hooks/docker-pre-commit"
    rev: "v2.0.0"
    hooks:
      - id: "hadolint-system"

  # "Helm chart linter"
  - repo: "https://github.com/gruntwork-io/pre-commit"
    rev: "v0.1.22"
    hooks:
      - id: "helmlint"


  - repo: "https://github.com/norwoodj/helm-docs"
    rev: "v1.11.0"
    hooks:
      - id: "helm-docs"
        args:
          - "--chart-search-root=helm"
          - "--template-files=README.md.gotmpl"

  - repo: "https://git.knut.univention.de/univention/infrastructure/pre-commit-hooks/addlicense"
    rev: "v1.0.1"
    hooks:
      - id: "addlicense"
        name: "Check or add license headers to files"

  - repo: "https://git.knut.univention.de/univention/customers/dataport/upx/kyverno-test-pre-commit"
    rev: "v0.1.0"
    hooks:
      - id: kyverno-test
...
