{{/*
SPDX-FileCopyrightText: 2023-2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}
{{ if .Values.provisioning.config.keycloak.password }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ printf "%s-keycloak-credentials" (include "common.names.fullname" .) }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}

stringData:
  {{ .Values.provisioning.config.keycloak.credentialSecret.key -}}: {{ .Values.provisioning.config.keycloak.password | quote }}
...
{{ end }}