{{/*
SPDX-FileCopyrightText: 2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- $_ := required "A Redis password has to be supplied, see parameter \"ics.redis.auth\"." (coalesce .Values.ics.redis.auth.password (.Values.ics.matrix.auth.existingSecret).name) }}
{{- if not (.Values.ics.redis.auth.existingSecret).name }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "redis" "context" .) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
    app.kubernetes.io/component: portal-server
  {{- if .Values.additionalAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
stringData:
  password: {{ .Values.ics.redis.auth.password | quote }}
{{- end }}
