{{/*
SPDX-FileCopyrightText: 2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- if ( and (not (.Values.ics.matrix.auth.existingSecret).name) .Values.ics.matrix.enabled ) }}
{{- $_ := required "A Matrix Application Secret has to be supplied, see parameter \"ics.matrix.auth\"." (coalesce .Values.ics.matrix.auth.applicationServiceSecret (.Values.ics.matrix.auth.existingSecret).name) }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "matrix" "context" .) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
    app.kubernetes.io/component: portal-server
  {{- if .Values.additionalAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
stringData:
  password: {{ .Values.ics.matrix.auth.applicationServiceSecret | quote }}
{{- end }}
