{{/*
SPDX-FileCopyrightText: 2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- $_ := required "A Keycloak password has to be supplied, see parameters \"provisioning.config.keycloak.auth\"." (coalesce .Values.provisioning.config.keycloak.auth.password (.Values.provisioning.config.keycloak.auth.existingSecret).name) }}
{{- if and (not (.Values.provisioning.config.keycloak.auth.existingSecret).name) .Values.provisioning.enabled }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "keycloak-provisioning" "context" .) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
    app.kubernetes.io/component: portal-server
  {{- if .Values.additionalAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
stringData:
  password: {{ .Values.provisioning.config.keycloak.auth.password | quote }}
{{- end }}
