{{/*
SPDX-FileCopyrightText: 2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- $_ := required "A central-navigation shared secret has to be supplied, see parameter \"ics.portal.auth\"." (coalesce .Values.ics.portal.auth.sharedSecret (.Values.ics.portal.auth.existingSecret).name) }}
{{- if ( and (not (.Values.ics.portal.auth.existingSecret).name) .Values.ics.portal.enabled ) }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "portal-central-navigation" "context" .) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
    app.kubernetes.io/component: portal-server
  {{- if .Values.additionalAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
stringData:
  sharedSecret: {{ .Values.ics.portal.auth.sharedSecret | quote }}
{{- end }}
