#!/bin/bash
#
# App unjoin script
#
# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH

## joinscript api: bindpwdfile

VERSION="2"
APP_ID="intercom-service"

. /usr/share/univention-lib/all.sh || exit 1
. /usr/share/univention-appcenter/joinscripthelper.sh || exit 1

joinscript_init

eval "$(ucr shell)"

# unset firewall rules
univention-config-registry unset \
  "security/packetfilter/package/$APP_ID/tcp/8008/all" \
  "security/packetfilter/package/$APP_ID/tcp/8008/en"

joinscript_remove_script_from_status_file "$APP_ID"
exit 0
